export const PAYLINES = [
  {
    id: 1,
    name: "Middle line",
    label: "Linie 1",
    rows: [1, 1, 1, 1, 1],
  },
  {
    id: 2,
    name: "Top line",
    label: "Linie 2",
    rows: [0, 0, 0, 0, 0],
  },
  {
    id: 3,
    name: "Bottom line",
    label: "Linie 3",
    rows: [2, 2, 2, 2, 2],
  },
  {
    id: 4,
    name: "V down",
    label: "Linie 4",
    rows: [0, 1, 2, 1, 0],
  },
  {
    id: 5,
    name: "V up",
    label: "Linie 5",
    rows: [2, 1, 0, 1, 2],
  },
  {
    id: 6,
    name: "Top small wave",
    label: "Linie 6",
    rows: [0, 0, 1, 0, 0],
  },
  {
    id: 7,
    name: "Bottom small wave",
    label: "Linie 7",
    rows: [2, 2, 1, 2, 2],
  },
  {
    id: 8,
    name: "Middle to top",
    label: "Linie 8",
    rows: [1, 0, 0, 0, 1],
  },
  {
    id: 9,
    name: "Middle to bottom",
    label: "Linie 9",
    rows: [1, 2, 2, 2, 1],
  },
  {
    id: 10,
    name: "Top to middle",
    label: "Linie 10",
    rows: [0, 1, 1, 1, 0],
  },
  {
    id: 11,
    name: "Bottom to middle",
    label: "Linie 11",
    rows: [2, 1, 1, 1, 2],
  },
  {
    id: 12,
    name: "Middle top zigzag",
    label: "Linie 12",
    rows: [1, 0, 1, 0, 1],
  },
  {
    id: 13,
    name: "Middle bottom zigzag",
    label: "Linie 13",
    rows: [1, 2, 1, 2, 1],
  },
  {
    id: 14,
    name: "Top zigzag",
    label: "Linie 14",
    rows: [0, 1, 0, 1, 0],
  },
  {
    id: 15,
    name: "Bottom zigzag",
    label: "Linie 15",
    rows: [2, 1, 2, 1, 2],
  },
  {
    id: 16,
    name: "Top to bottom slope",
    label: "Linie 16",
    rows: [0, 0, 1, 2, 2],
  },
  {
    id: 17,
    name: "Bottom to top slope",
    label: "Linie 17",
    rows: [2, 2, 1, 0, 0],
  },
  {
    id: 18,
    name: "Top drop",
    label: "Linie 18",
    rows: [0, 1, 2, 2, 2],
  },
  {
    id: 19,
    name: "Bottom rise",
    label: "Linie 19",
    rows: [2, 1, 0, 0, 0],
  },
  {
    id: 20,
    name: "Middle top bump",
    label: "Linie 20",
    rows: [1, 1, 0, 1, 1],
  },
  {
    id: 21,
    name: "Middle bottom bump",
    label: "Linie 21",
    rows: [1, 1, 2, 1, 1],
  },
  {
    id: 22,
    name: "Top to bottom bridge",
    label: "Linie 22",
    rows: [0, 1, 1, 1, 2],
  },
  {
    id: 23,
    name: "Bottom to top bridge",
    label: "Linie 23",
    rows: [2, 1, 1, 1, 0],
  },
  {
    id: 24,
    name: "Sharp top pattern",
    label: "Linie 24",
    rows: [0, 2, 0, 2, 0],
  },
  {
    id: 25,
    name: "Sharp bottom pattern",
    label: "Linie 25",
    rows: [2, 0, 2, 0, 2],
  },
];